---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
  options:
    config-file: molecule/default/.yamllint
platforms:
    - name: centos7
      image: jgeusebroek/centos7-molecule
      image_version: latest
      pre_build_image: true
      ansible_groups:
        - redhat
    - name: debian8
      image: jgeusebroek/debian8-molecule
      image_version: latest
      pre_build_image: true
      ansible_groups:
        - debian
    - name: debian9
      image: jgeusebroek/debian9-molecule
      image_version: latest
      pre_build_image: true
      ansible_groups:
        - debian
    - name: ubuntu1604
      image: jgeusebroek/ubuntu1604-molecule
      image_version: latest
      pre_build_image: true
      ansible_groups:
        - ubuntu
    - name: ubuntu1804
      image: jgeusebroek/ubuntu1804-molecule
      image_version: latest
      pre_build_image: true
      ansible_groups:
        - ubuntu
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
