---
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/default/yamllint.yml .
  ansible-lint
  flake8
platforms:
  - name: "${MOLECULE_DISTRO:-centos7}"
    image: "jgeusebroek/${MOLECULE_DISTRO:-centos7}-molecule:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
